### ISSUE TITLE
ClassLoaderI18n throw NPE

### ISSUE THREAD

**Issue by mouse0w0** [UnknownStudio/UDPLib#12]
```
[12:27:06] [Server thread/ERROR]: [UDPLib] Cannot read language file from class path
java.lang.NullPointerException
	at team.unstudio.udpl.i18n.ClassLoaderI18n.reload(ClassLoaderI18n.java:51) [UDPLib.jar:?]
	at team.unstudio.udpl.i18n.ClassLoaderI18n.<init>(ClassLoaderI18n.java:32) [UDPLib.jar:?]
	at team.unstudio.udpl.core.UDPLI18n.<clinit>(UDPLI18n.java:12) [UDPLib.jar:?]
	at team.unstudio.udpl.command.anno.AnnoCommandManager.<clinit>(AnnoCommandManager.java:23) [UDPLib.jar:?]
	at team.unstudio.udpl.core.UDPLib.loadPluginManager(UDPLib.java:83) [UDPLib.jar:?]
	at team.unstudio.udpl.core.UDPLib.onEnable(UDPLib.java:67) [UDPLib.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-a3f6ea5-6194f6c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-a3f6ea5-6194f6c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-a3f6ea5-6194f6c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-a3f6ea5-6194f6c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-a3f6ea5-6194f6c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-a3f6ea5-6194f6c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-a3f6ea5-6194f6c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-a3f6ea5-6194f6c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-a3f6ea5-6194f6c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-a3f6ea5-6194f6c]
```

**Comment by mouse0w0** [comment]
But ClassLoaderI18n isn't avaliable.

**Comment by LasmGratel** [comment]
Well, Bukkit uses a different ClassLoader, so we might have to export UDPLib language files to a temp folder.
